version: '3'

volumes:
  MDB-local:

services:
  MDB-local:
    container_name: MDB-local
    image: mongo:4.4-bionic
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=userpwd
      - MONGO_INITDB_DATABASE=commondb
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./MDB/:/data/db
    ports:
      - 27017:27017
