version: '3'

volumes:
  CADB-local:

services:
  CADB-local:
    container_name: CADB-local
    image: mongo:${COMMON_ADAPTER_MONGO_VERSION}
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${COMMON_ADAPTER_MONGO_ROOT}
      - MONGO_INITDB_ROOT_PASSWORD=${COMMON_ADAPTER_MONGO_ROOTPW}
      - MONGO_INITDB_DATABASE=commondb
    volumes:
      - ${COMMON_ADAPTER_MONGO_PV_PATH}/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ${COMMON_ADAPTER_MONGO_PV_PATH}:/data/db
    ports:
      - ${COMMON_ADAPTER_MONGO_PORT}:27017

  common-adapter-local:
    container_name: common-adapter-local
    build: ./server
    image: common-adapter:${COMMON_ADAPTER_TAG}
    restart: always
    environment:
      - COMMON_ADAPTER_LOG_LEVEL=${COMMON_ADAPTER_LOG_LEVEL}
      - COMMON_ADAPTER_DB_URL=mongodb://${COMMON_ADAPTER_MONGO_USER}:${COMMON_ADAPTER_MONGO_USERPW}@${COMMON_ADAPTER_MONGO_DB_HOST}:${COMMON_ADAPTER_MONGO_PORT}/commondb?authSource=commondb
      - COMMON_ADAPTER_BLOCKCHAIN_ADAPTER_URL=${COMMON_ADAPTER_BLOCKCHAIN_ADAPTER_URL}
    depends_on:
      - CADB-local
    ports:
      - ${COMMON_ADAPTER_PORT}:3000
