version: '3'

services:
  CADB-dtag:
    container_name: CADB-dtag
    image: mongo:${COMMON_ADAPTER_MONGO_VERSION}
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DTAG_COMMON_ADAPTER_MONGO_ROOT}
      - MONGO_INITDB_ROOT_PASSWORD=${DTAG_COMMON_ADAPTER_MONGO_ROOTPW}
      - MONGO_INITDB_DATABASE=commondb
    volumes:
      - ${DTAG_COMMON_ADAPTER_MONGO_PV_PATH}/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ${DTAG_COMMON_ADAPTER_MONGO_PV_PATH}:/data/db
    ports:
      - ${DTAG_COMMON_ADAPTER_MONGO_PORT}:27017
    networks:
      - nomad


  common-adapter-dtag:
    container_name: common-adapter-dtag
    build: common-adapter/server
    image: common-adapter
    restart: always
    environment:
      - COMMON_ADAPTER_LOG_LEVEL=${DTAG_COMMON_ADAPTER_LOG_LEVEL}
      - COMMON_ADAPTER_DB_URL=mongodb://${DTAG_COMMON_ADAPTER_MONGO_USER}:${DTAG_COMMON_ADAPTER_MONGO_USERPW}@CADB-dtag:27017/commondb?authSource=commondb
      - COMMON_ADAPTER_BLOCKCHAIN_ADAPTER_URL=${DTAG_COMMON_ADAPTER_BLOCKCHAIN_ADAPTER_URL}
    depends_on:
      - CADB-dtag
    ports:
      - ${DTAG_COMMON_ADAPTER_PORT}:3000
    networks:
      - nomad


  CADB-tmus:
    container_name: CADB-tmus
    image: mongo:${COMMON_ADAPTER_MONGO_VERSION}
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${TMUS_COMMON_ADAPTER_MONGO_ROOT}
      - MONGO_INITDB_ROOT_PASSWORD=${TMUS_COMMON_ADAPTER_MONGO_ROOTPW}
      - MONGO_INITDB_DATABASE=commondb
    volumes:
      - ${TMUS_COMMON_ADAPTER_MONGO_PV_PATH}/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ${TMUS_COMMON_ADAPTER_MONGO_PV_PATH}:/data/db
    ports:
      - ${TMUS_COMMON_ADAPTER_MONGO_PORT}:27017
    networks:
      - nomad


  common-adapter-tmus:
    container_name: common-adapter-tmus
    build: common-adapter/server
    image: common-adapter
    restart: always
    environment:
      - COMMON_ADAPTER_LOG_LEVEL=${TMUS_COMMON_ADAPTER_LOG_LEVEL}
      - COMMON_ADAPTER_DB_URL=mongodb://${TMUS_COMMON_ADAPTER_MONGO_USER}:${TMUS_COMMON_ADAPTER_MONGO_USERPW}@CADB-tmus:27017/commondb?authSource=commondb
      - COMMON_ADAPTER_BLOCKCHAIN_ADAPTER_URL=${TMUS_COMMON_ADAPTER_BLOCKCHAIN_ADAPTER_URL}
      - 'COMMON_ADAPTER_BLOCKCHAIN_ADAPTER_WEBHOOKS=[{"eventName": "STORE:DOCUMENTHASH", "callbackUrl": "http://common-adapter-tmus:3000/api/v1/contracts/event/"},{"eventName": "STORE:SIGNATURE", "callbackUrl": "http://common-adapter-tmus:3000/api/v1/contracts/event/"}]'
    depends_on:
      - CADB-tmus
    ports:
      - ${TMUS_COMMON_ADAPTER_PORT}:3000
    networks:
      - nomad
      